# Generated by Django 5.2.1 on 2025-05-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NonVegDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning Services'), ('maintenance', 'Maintenance & Repairs'), ('gardening', 'Gardening & Landscaping'), ('automation', 'Home Automation'), ('security', 'Security Services'), ('cooking', 'Cooking Services')], max_length=20)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_option', models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning')], max_length=20, null=True)),
                ('maintenance_option', models.CharField(blank=True, choices=[('plumbing', 'Plumbing Repairs'), ('electrical', 'Electrical Repairs'), ('carpentry', 'Carpentry Work'), ('painting', 'Painting Services'), ('appliance', 'Appliance Repair'), ('hvac', 'HVAC Maintenance'), ('roof', 'Roof Repairs'), ('pest', 'Pest Control'), ('locksmith', 'Locksmith Services')], max_length=20, null=True)),
                ('gardening_option', models.CharField(blank=True, choices=[('lawn', 'Lawn Maintenance'), ('garden', 'Garden Design'), ('irrigation', 'Irrigation Systems'), ('tree', 'Tree Services'), ('landscaping', 'Landscaping'), ('planting', 'Plant Installation'), ('mulching', 'Mulching Services'), ('fertilization', 'Fertilization Services'), ('weed_control', 'Weed Control')], max_length=20, null=True)),
                ('automation_option', models.CharField(blank=True, choices=[('lighting', 'Smart Lighting'), ('security', 'Security Systems'), ('climate', 'Climate Control'), ('entertainment', 'Home Entertainment'), ('voice', 'Voice Control Systems'), ('door_locks', 'Smart Door Locks'), ('cameras', 'Smart Cameras'), ('speakers', 'Smart Speakers'), ('appliances', 'Smart Appliances')], max_length=20, null=True)),
                ('security_option', models.CharField(blank=True, choices=[('cctv', 'CCTV Installation'), ('alarm', 'Alarm Systems'), ('access', 'Access Control'), ('monitoring', '24/7 Monitoring'), ('consultation', 'Security Consultation'), ('fire_safety', 'Fire Safety Systems'), ('intercom', 'Intercom Systems'), ('biometric', 'Biometric Security'), ('smart_locks', 'Smart Lock Installation')], max_length=20, null=True)),
                ('cooking_option', models.CharField(blank=True, choices=[('veg', 'Vegetarian Dishes'), ('non_veg', 'Non-Vegetarian Dishes')], max_length=20, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('area_coverage', models.CharField(blank=True, choices=[('studio', 'Studio Apartment (300-500 sq ft)'), ('1bhk', '1 BHK (500-800 sq ft)'), ('2bhk', '2 BHK (800-1200 sq ft)'), ('3bhk', '3 BHK (1200-1800 sq ft)'), ('4bhk', '4 BHK (1800-2500 sq ft)'), ('villa', 'Villa (2500+ sq ft)'), ('commercial_small', 'Small Commercial (500-1000 sq ft)'), ('commercial_medium', 'Medium Commercial (1000-2000 sq ft)'), ('commercial_large', 'Large Commercial (2000+ sq ft)')], max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use')], max_length=20, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=20, null=True)),
                ('square_footage', models.IntegerField(blank=True, help_text='Exact square footage of the property', null=True)),
                ('floor_count', models.IntegerField(blank=True, help_text='Number of floors in the property', null=True)),
                ('includes', models.TextField(blank=True, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning Services'), ('maintenance', 'Maintenance & Repairs'), ('gardening', 'Gardening & Landscaping'), ('automation', 'Home Automation'), ('security', 'Security Services'), ('cooking', 'Cooking Services')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('cleaning_option', models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning')], max_length=20, null=True)),
                ('maintenance_option', models.CharField(blank=True, choices=[('plumbing', 'Plumbing Repairs'), ('electrical', 'Electrical Repairs'), ('carpentry', 'Carpentry Work'), ('painting', 'Painting Services'), ('appliance', 'Appliance Repair'), ('hvac', 'HVAC Maintenance'), ('roof', 'Roof Repairs'), ('pest', 'Pest Control'), ('locksmith', 'Locksmith Services')], max_length=20, null=True)),
                ('gardening_option', models.CharField(blank=True, choices=[('lawn', 'Lawn Maintenance'), ('garden', 'Garden Design'), ('irrigation', 'Irrigation Systems'), ('tree', 'Tree Services'), ('landscaping', 'Landscaping'), ('planting', 'Plant Installation'), ('mulching', 'Mulching Services'), ('fertilization', 'Fertilization Services'), ('weed_control', 'Weed Control')], max_length=20, null=True)),
                ('automation_option', models.CharField(blank=True, choices=[('lighting', 'Smart Lighting'), ('security', 'Security Systems'), ('climate', 'Climate Control'), ('entertainment', 'Home Entertainment'), ('voice', 'Voice Control Systems'), ('door_locks', 'Smart Door Locks'), ('cameras', 'Smart Cameras'), ('speakers', 'Smart Speakers'), ('appliances', 'Smart Appliances')], max_length=20, null=True)),
                ('security_option', models.CharField(blank=True, choices=[('cctv', 'CCTV Installation'), ('alarm', 'Alarm Systems'), ('access', 'Access Control'), ('monitoring', '24/7 Monitoring'), ('consultation', 'Security Consultation'), ('fire_safety', 'Fire Safety Systems'), ('intercom', 'Intercom Systems'), ('biometric', 'Biometric Security'), ('smart_locks', 'Smart Lock Installation')], max_length=20, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('service_areas', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VegDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dish_type', models.CharField(choices=[('chapati_curry', 'Chapati + Curry'), ('paratha', 'Paratha')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
