# Generated by Django 5.2.1 on 2025-05-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_booking_total_price_booking_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='combo_type',
            field=models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='nonveg_curry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_as_nonveg_curry', to='core.nonvegdish'),
        ),
        migrations.AddField(
            model_name='booking',
            name='veg_curry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_as_veg_curry', to='core.vegdish'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_as_dish', to='core.vegdish'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='non_veg_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_as_non_veg_dish', to='core.nonvegdish'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bread'),
        ),
    ]
