# Generated by Django 5.2.1 on 2025-05-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bread_booking_combo_type_booking_nonveg_curry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bread',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='combo_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='nonveg_curry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='veg_curry',
        ),
    ]
