# Generated by Django 5.2.1 on 2025-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_booking_bread_remove_booking_combo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
