# Generated by Django 5.2 on 2025-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('garden', 'Garden'), ('home_appliance', 'Home Appliance'), ('security', 'Security'), ('food', 'Food')], max_length=20)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
