# Generated by Django 5.2 on 2025-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
