# Generated by Django 5.2 on 2025-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicerequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='appliance_type',
            field=models.CharField(blank=True, help_text='Type of appliance needing service', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='area_size',
            field=models.CharField(blank=True, help_text='Size of the area to be cleaned (e.g., 1000 sq ft)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the appliance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cleaning_frequency',
            field=models.CharField(blank=True, help_text='How often the cleaning service is needed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cuisine',
            field=models.CharField(blank=True, help_text='Preferred cuisine', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Any dietary restrictions', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='equipment_age',
            field=models.CharField(blank=True, help_text='Age of the equipment needing maintenance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='existing_equipment',
            field=models.TextField(blank=True, help_text='Existing security equipment', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='garden_size',
            field=models.CharField(blank=True, help_text='Size of the garden', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='garden_type',
            field=models.CharField(blank=True, help_text='Type of garden (e.g., vegetable, flower, lawn)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='issue_description',
            field=models.TextField(blank=True, help_text='Detailed description of the issue', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='maintenance_type',
            field=models.CharField(blank=True, help_text='Type of maintenance required', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='meal_type',
            field=models.CharField(blank=True, help_text='Type of meal (e.g., breakfast, lunch, dinner)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='model',
            field=models.CharField(blank=True, help_text='Model of the appliance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='number_of_people',
            field=models.IntegerField(blank=True, help_text='Number of people to be served', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='property_size',
            field=models.CharField(blank=True, help_text='Size of the property', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='security_system_type',
            field=models.CharField(blank=True, help_text='Type of security system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_frequency',
            field=models.CharField(blank=True, help_text='How often the garden service is needed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special cleaning requirements', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='urgency_level',
            field=models.CharField(blank=True, help_text='Urgency level of the maintenance request', max_length=20, null=True),
        ),
    ]
