# Generated by Django 5.2 on 2025-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicerequest_appliance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingservice',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
