# Generated by Django 5.2 on 2025-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cookingservice_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingservice',
            name='chef_speciality',
            field=models.BooleanField(default=False, help_text="Mark if this is a chef's speciality"),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('indian', 'Indian'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('continental', 'Continental'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='dietary_info',
            field=models.TextField(blank=True, help_text='Dietary information (e.g., gluten-free, dairy-free)', null=True),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Main ingredients used', null=True),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('all_day', 'All Day')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='preparation_time',
            field=models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='serving_size',
            field=models.IntegerField(blank=True, help_text='Number of people this dish serves', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='automation_option',
            field=models.CharField(blank=True, choices=[('lighting', 'Smart Lighting'), ('security', 'Security Systems'), ('climate', 'Climate Control'), ('entertainment', 'Home Entertainment'), ('voice', 'Voice Control Systems'), ('door_locks', 'Smart Door Locks'), ('cameras', 'Smart Cameras'), ('speakers', 'Smart Speakers'), ('appliances', 'Smart Appliances')], help_text='Select the specific home automation service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cleaning_option',
            field=models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning')], help_text='Select the specific cleaning service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cooking_option',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian Dishes'), ('non_veg', 'Non-Vegetarian Dishes')], help_text='Select the specific cooking service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='gardening_option',
            field=models.CharField(blank=True, choices=[('lawn', 'Lawn Maintenance'), ('garden', 'Garden Design'), ('irrigation', 'Irrigation Systems'), ('tree', 'Tree Services'), ('landscaping', 'Landscaping'), ('planting', 'Plant Installation'), ('mulching', 'Mulching Services'), ('fertilization', 'Fertilization Services'), ('weed_control', 'Weed Control')], help_text='Select the specific gardening service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='maintenance_option',
            field=models.CharField(blank=True, choices=[('plumbing', 'Plumbing Repairs'), ('electrical', 'Electrical Repairs'), ('carpentry', 'Carpentry Work'), ('painting', 'Painting Services'), ('appliance', 'Appliance Repair'), ('hvac', 'HVAC Maintenance'), ('roof', 'Roof Repairs'), ('pest', 'Pest Control'), ('locksmith', 'Locksmith Services')], help_text='Select the specific maintenance service', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='security_option',
            field=models.CharField(blank=True, choices=[('cctv', 'CCTV Installation'), ('alarm', 'Alarm Systems'), ('access', 'Access Control'), ('monitoring', '24/7 Monitoring'), ('consultation', 'Security Consultation'), ('fire_safety', 'Fire Safety Systems'), ('intercom', 'Intercom Systems'), ('biometric', 'Biometric Security'), ('smart_locks', 'Smart Lock Installation')], help_text='Select the specific security service', max_length=20, null=True),
        ),
    ]
