# Generated by Django 5.2 on 2025-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cookingservice_chef_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='area_coverage',
        ),
        migrations.RemoveField(
            model_name='service',
            name='property_type',
        ),
        migrations.AddField(
            model_name='cookingservice',
            name='cooking_option',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian Dishes'), ('non_veg', 'Non-Vegetarian Dishes')], help_text='Select the specific cooking service', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vegdish',
            name='dish_type',
            field=models.CharField(choices=[('chapati_curry', 'Chapati + Curry'), ('paratha', 'Paratha'), ('rice_curry', 'Rice + Curry'), ('thali', 'Thali'), ('snacks', 'Snacks'), ('dessert', 'Dessert')], max_length=20),
        ),
    ]
