# Generated by Django 5.2.1 on 2025-05-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_service_area_coverage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='repayment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookingservice',
            name='cooking_option',
            field=models.CharField(blank=True, choices=[('Daily Home Cook', 'daily_home_cook'), ('Event/Party Catering', 'event_party_catering'), ('Kids Meal Service', 'kids_meal_service'), ('Personal Chef at Home', 'personal_chef_at_home'), ('Specialty Cuisine Cooking', 'specialty_cuisine_cooking'), ('Tiffin Services', 'tiffin_services')], help_text='Select the specific cooking service', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('googlepay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'PayTM'), ('debitcard', 'Debit Card'), ('creditcard', 'Credit Card'), ('cod', 'Cash on Delivery'), ('paylater', 'Pay Later'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('emi', 'EMI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='cooking_option',
            field=models.CharField(blank=True, choices=[('Daily Home Cook', 'daily_home_cook'), ('Event/Party Catering', 'event_party_catering'), ('Kids Meal Service', 'kids_meal_service'), ('Personal Chef at Home', 'personal_chef_at_home'), ('Specialty Cuisine Cooking', 'specialty_cuisine_cooking'), ('Tiffin Services', 'tiffin_services')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='cooking_option',
            field=models.CharField(blank=True, choices=[('Daily Home Cook', 'daily_home_cook'), ('Event/Party Catering', 'event_party_catering'), ('Kids Meal Service', 'kids_meal_service'), ('Personal Chef at Home', 'personal_chef_at_home'), ('Specialty Cuisine Cooking', 'specialty_cuisine_cooking'), ('Tiffin Services', 'tiffin_services')], help_text='Select the specific cooking service', max_length=30, null=True),
        ),
    ]
