# Generated by Django 5.2 on 2026-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payment_options_payment_card_last_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cleaning_option',
            field=models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning'), ('home', 'Home Cleaning')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='cleaning_option',
            field=models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning'), ('home', 'Home Cleaning')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='cleaning_option',
            field=models.CharField(blank=True, choices=[('regular', 'Regular House Cleaning'), ('deep', 'Deep Cleaning'), ('carpet', 'Carpet and Upholstery Cleaning'), ('window', 'Window Cleaning'), ('move', 'Move-in/Move-out Cleaning'), ('home', 'Home Cleaning')], help_text='Select the specific cleaning service', max_length=20, null=True),
        ),
    ]
