# Generated by Django 5.2 on 2026-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_service_cleaning_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_name',
            field=models.CharField(blank=True, default='', help_text='Enter the static filename from static/images/services/ (leave blank to use fallback image mapping)', max_length=100),
        ),
    ]
