# Generated by Django 5.2 on 2026-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.CharField(blank=True, default='default.jpg', help_text='Enter image filename from static/images/services/', max_length=100),
        ),
    ]
